# Gradle & JVM Optimizations
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Kotlin & KSP Optimizations
kotlin.incremental=true
kotlin.caching.enabled=true
ksp.incremental=true
ksp.incremental.intermodule=true

# Android Gradle Plugin Options
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.disallowKotlinSourceSets=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED,GENERIC
